#!/bin/bash

CMD_PATH="$(readlink -f "$0")"
CMD_DIR="$(dirname "$CMD_PATH")"
TYPE="markdown"

usage() {
  cat >&2 <<EOF
使い方: $(basename "$0") [-o NAME] [-h]

  -o NAME   作成後に NAME へリネームするのだ
  -h        このヘルプを表示するのだ
EOF
  exit 2
}

while getopts ":o:h" OPT; do
    case $OPT in
        o ) RENAME="TRUE" ; NAME="$OPTARG" ;;
        h ) usage ;;
        : ) echo "オプション -$OPTARG には引数が必要なのだ" >&2; usage ;;
        \? ) "不明なオプション: -$OPT" >&2; usage ;;
    esac
done

cp -r $CMD_DIR/../$TYPE $PWD

if [ "$RENAME" ]; then
    mv $PWD/$TYPE $PWD/$NAME
else
    NAME=$TYPE
fi

echo "$NAMEを作成しました"
